"""Curated historical story catalog for History Bot V3.
Every item is intentionally compact and conservative: the writer receives only
these facts and must not invent details. Visual queries prefer documentary/contextual
photographs and real objects over decorative illustrations.
"""

EVENTS = [
# Calendar events
{"id":"napoleon-moscow-1812","month":9,"day":14,"year":1812,"type":"event_today","title":"День, когда Наполеон вошёл в Москву","event":"14 сентября 1812 года французская армия вошла в Москву после того, как русские войска оставили город.","facts":["Наполеон рассчитывал, что взятие Москвы поможет завершить кампанию политически.","Российский император Александр I не согласился на мир на условиях Наполеона.","Вскоре французская армия начала отступление из России."],"angle":"Он получил Москву, но не получил главного — мира.","importance":10,"drama":9,"visual":["Napoleon Moscow 1812 Kremlin historical","Moscow 1812 historical photograph Kremlin","Napoleon portrait photograph museum"],"visual_kind":"context"},
{"id":"luna2-1959","month":9,"day":14,"year":1959,"type":"breakthrough","title":"Первый аппарат, достигший Луны","event":"14 сентября 1959 года советская автоматическая станция «Луна-2» достигла поверхности Луны.","facts":["Это был первый созданный человеком объект, достигший другого небесного тела.","Миссия стала важной вехой ранней космической гонки."],"angle":"В этот день космос впервые перестал быть недосягаемой точкой на небе.","importance":9,"drama":7,"visual":["Luna 2 1959 Soviet spacecraft photograph","Luna 2 model museum photograph","Soviet Luna program archive"],"visual_kind":"photo"},
{"id":"sarajevo-1914","month":6,"day":28,"year":1914,"type":"assassination","title":"Выстрел в Сараево","event":"28 июня 1914 года в Сараево был убит наследник австро-венгерского престола Франц Фердинанд.","facts":["Убийство стало непосредственным политическим кризисом между Австро-Венгрией и Сербией.","Последовавшая цепь дипломатических и военных решений привела к Первой мировой войне."],"angle":"Один выстрел не объясняет всю войну, но стал спусковым крючком кризиса, изменившего мир.","importance":10,"drama":10,"visual":["Franz Ferdinand Sarajevo 1914 photograph","Sarajevo 1914 historical photograph","Franz Ferdinand archive photo"],"visual_kind":"photo"},
{"id":"gagarin-1961","month":4,"day":12,"year":1961,"type":"breakthrough","title":"108 минут, которые изменили представление о человеке","event":"12 апреля 1961 года Юрий Гагарин совершил первый в истории пилотируемый космический полёт.","facts":["Полёт на корабле «Восток-1» длился 108 минут.","Гагарин стал первым человеком, побывавшим в космосе."],"angle":"До этого дня никто не видел Землю из космоса глазами человека.","importance":10,"drama":8,"visual":["Yuri Gagarin 1961 photograph","Vostok 1 historical photograph","Gagarin archive photo 1961"],"visual_kind":"photo"},
{"id":"apollo11-1969","month":7,"day":20,"year":1969,"type":"breakthrough","title":"День, когда человек ступил на Луну","event":"20 июля 1969 года астронавты миссии Apollo 11 достигли Луны; Нил Армстронг и Базз Олдрин работали на её поверхности.","facts":["Apollo 11 стала первой пилотируемой миссией, доставившей людей на Луну.","Событие стало одним из символов космической гонки XX века."],"angle":"Мечта, существовавшая тысячелетиями, внезапно стала фотографией и следом на лунном грунте.","importance":10,"drama":9,"visual":["Apollo 11 Moon landing photograph","Buzz Aldrin Moon NASA photograph","Neil Armstrong Apollo 11 archive"],"visual_kind":"photo"},
{"id":"berlin-wall-1989","month":11,"day":9,"year":1989,"type":"event_today","title":"Ночь, когда Берлинская стена перестала разделять город","event":"9 ноября 1989 года власти ГДР объявили о новых правилах выезда, после чего жители Восточного и Западного Берлина массово собрались у пограничных переходов.","facts":["Открытие границы стало символом конца разделения Германии.","Падение стены стало одним из ключевых символов завершения холодной войны в Европе."],"angle":"Иногда граница существует десятилетиями, а затем история ломает её за одну ночь.","importance":10,"drama":9,"visual":["Berlin Wall fall 1989 photograph","Berlin Wall Brandenburg Gate 1989 archive","East Berlin 1989 wall photo"],"visual_kind":"photo"},
{"id":"titanic-1912","month":4,"day":15,"year":1912,"type":"catastrophe","title":"Последняя ночь «Титаника»","event":"В ночь с 14 на 15 апреля 1912 года лайнер RMS Titanic столкнулся с айсбергом в Северной Атлантике и затонул.","facts":["Катастрофа стала одной из самых известных морских трагедий XX века.","После гибели «Титаника» международные требования к безопасности судоходства были усилены."],"angle":"Символ технической эпохи столкнулся с одной ледяной глыбой — и изменил правила мореплавания.","importance":10,"drama":10,"visual":["RMS Titanic 1912 photograph","Titanic Southampton departure photograph","Titanic survivors Carpathia archive"],"visual_kind":"photo"},
{"id":"caesar-44bc","month":3,"day":15,"year":-44,"type":"last_day","title":"Последний день Юлия Цезаря","event":"15 марта 44 года до н. э. Юлий Цезарь был убит группой заговорщиков в Риме.","facts":["Убийство произошло в период тяжёлого политического кризиса Римской республики.","Последовавшие гражданские войны привели к установлению принципата при Октавиане Августе."],"angle":"Заговорщики хотели спасти республику, но после их удара республика уже не вернулась к прежнему состоянию.","importance":10,"drama":10,"visual":["Julius Caesar bust museum photograph","Roman Forum photograph Caesar","Theatre of Pompey ruins photograph"],"visual_kind":"context"},
{"id":"constantinople-1453","month":5,"day":29,"year":1453,"type":"last_day","title":"Последний день Константинополя","event":"29 мая 1453 года османские войска захватили Константинополь, завершив существование Византийской империи.","facts":["Константинополь был столицей Византии более тысячи лет.","Падение города изменило политическую карту Восточного Средиземноморья."],"angle":"Город пережил века войн, но последняя осада закрыла целую историческую эпоху.","importance":10,"drama":10,"visual":["Hagia Sophia Istanbul historical photograph","Constantinople walls photograph","Theodosian Walls Istanbul photograph"],"visual_kind":"context"},
{"id":"d-day-1944","month":6,"day":6,"year":1944,"type":"great_battle","title":"День, когда союзники вернулись в Европу","event":"6 июня 1944 года союзные войска начали высадку в Нормандии.","facts":["Операция стала крупнейшей морской десантной операцией в истории.","Высадка открыла западный фронт в Западной Европе против нацистской Германии."],"angle":"Над Ла-Маншем началась операция, от исхода которой зависело, как будет выглядеть послевоенная Европа.","importance":10,"drama":10,"visual":["D-Day Normandy 1944 photograph","Omaha Beach June 6 1944 archive","Normandy landings historical photo"],"visual_kind":"photo"},
{"id":"stalingrad-1943","month":2,"day":2,"year":1943,"type":"great_battle","title":"Сталинград: точка, после которой война изменилась","event":"2 февраля 1943 года завершилась Сталинградская битва капитуляцией окружённой немецкой группировки.","facts":["Сражение стало одним из крупнейших и самых ожесточённых во Второй мировой войне.","Победа СССР стала важнейшим стратегическим переломом на Восточном фронте."],"angle":"Битва за один город стала точкой, после которой война уже не могла идти по прежнему сценарию.","importance":10,"drama":10,"visual":["Stalingrad 1942 1943 historical photograph","Stalingrad battle archive photo ruins","German soldiers Stalingrad archive"],"visual_kind":"photo"},
{"id":"waterloo-1815","month":6,"day":18,"year":1815,"type":"great_battle","title":"Ватерлоо: последние часы Наполеона как императора","event":"18 июня 1815 года армия Наполеона потерпела поражение при Ватерлоо от союзных войск.","facts":["Поражение положило конец кампании Ста дней.","После Ватерлоо Наполеон вскоре вновь отрёкся от престола."],"angle":"Одна битва не уничтожила его имя, но закрыла последнюю попытку вернуть империю.","importance":10,"drama":10,"visual":["Waterloo battlefield photograph","Waterloo monument historical photograph","Napoleon 1815 portrait museum"],"visual_kind":"context"},
{"id":"borodino-1812","month":9,"day":7,"year":1812,"type":"great_battle","title":"Бородино: день, когда победа не дала ответа","event":"7 сентября 1812 года состоялось Бородинское сражение между русской армией и армией Наполеона.","facts":["Сражение стало одним из самых кровопролитных однодневных боёв XIX века.","После битвы русская армия отступила, но война не завершилась."],"angle":"Наполеон выиграл поле боя, но не выиграл войну.","importance":10,"drama":10,"visual":["Borodino battlefield photograph","Borodino museum panorama historical","Borodino monuments photograph"],"visual_kind":"context"},
{"id":"cannae-216bc","type":"great_battle","title":"Канны: ловушка, в которую вошла армия Рима","event":"В 216 году до н. э. армия Ганнибала разгромила римлян в битве при Каннах, применив двойное окружение.","facts":["Римская армия имела численное превосходство.","Манёвр Ганнибала при Каннах стал классическим примером окружения противника."],"angle":"Римляне шли вперёд — и сами оказались внутри смертельной ловушки.","importance":10,"drama":10,"visual":["Cannae battlefield Italy photograph","Canne della Battaglia archaeological site photograph","Hannibal bust museum photograph"],"visual_kind":"context"},
{"id":"pompeii-79","type":"catastrophe","title":"Город, который исчез и сохранился одновременно","event":"Извержение Везувия в 79 году н. э. уничтожило Помпеи и другие поселения у Неаполитанского залива.","facts":["Катастрофа сохранила многие элементы повседневной жизни античного города под слоями вулканических материалов.","Помпеи стали одним из важнейших археологических памятников античности."],"angle":"Катастрофа уничтожила город — и одновременно законсервировала его жизнь для будущих веков.","importance":10,"drama":10,"visual":["Pompeii ruins photograph","Pompeii street archaeological photograph","Mount Vesuvius Pompeii photo"],"visual_kind":"photo"},
{"id":"chernobyl-1986","month":4,"day":26,"year":1986,"type":"catastrophe","title":"Ночь, после которой мир пересмотрел цену атомной энергии","event":"26 апреля 1986 года на Чернобыльской АЭС произошла авария на четвёртом энергоблоке.","facts":["Авария стала крупнейшей в истории атомной энергетики.","Последствия потребовали масштабной ликвидации и долгосрочных мер по защите населения и окружающей среды."],"angle":"Одна ночь превратила технический объект в символ глобальной катастрофы.","importance":10,"drama":10,"visual":["Chernobyl 1986 archive photograph","Pripyat Chernobyl historical photo","Chernobyl liquidators photograph"],"visual_kind":"photo"},
{"id":"hindenburg-1937","month":5,"day":6,"year":1937,"type":"catastrophe","title":"33 секунды, которые изменили судьбу дирижаблей","event":"6 мая 1937 года дирижабль «Гинденбург» загорелся и потерпел катастрофу при посадке в Лейкхерсте.","facts":["Катастрофа была снята и сфотографирована многочисленными очевидцами.","Гибель «Гинденбурга» стала символом конца эпохи пассажирских дирижаблей."],"angle":"Будущее воздушных путешествий горело на глазах у камер.","importance":9,"drama":10,"visual":["Hindenburg disaster 1937 photograph","Hindenburg Lakehurst archive photo","Hindenburg airship photograph"],"visual_kind":"photo"},
{"id":"franklin-expedition","type":"mystery","title":"Экспедиция, которая ушла в Арктику и исчезла","event":"Экспедиция Джона Франклина отправилась в Арктику в 1845 году; оба корабля были потеряны, а судьба участников долго оставалась загадкой.","facts":["Экспедиция состояла из кораблей HMS Erebus и HMS Terror.","Останки кораблей были обнаружены уже в XXI веке."],"angle":"Они ушли искать путь через Арктику. Ответ на вопрос «что произошло?» собирали почти два века.","importance":8,"drama":10,"visual":["Franklin expedition Erebus Terror photograph","HMS Erebus wreck underwater photograph","John Franklin portrait photograph"],"visual_kind":"context"},
{"id":"roanoke","type":"mystery","title":"Колония, которая исчезла","event":"Английская колония Роанок в Северной Америке исчезла в конце XVI века; точные обстоятельства остаются предметом исследований.","facts":["Когда Джон Уайт вернулся в колонию в 1590 году, поселенцев там не было.","Слово CROATOAN стало одной из самых известных загадок этой истории."],"angle":"Люди исчезли, а одна надпись пережила их как вопрос без окончательного ответа.","importance":7,"drama":9,"visual":["Roanoke Island historical site photograph","Fort Raleigh National Historic Site photograph","Roanoke archaeological site photo"],"visual_kind":"context"},
{"id":"franz-joseph","type":"person_story","title":"Император, переживший почти весь XIX век","event":"Франц Иосиф I правил Австрией и Австро-Венгрией с 1848 по 1916 год.","facts":["За годы его правления Европа пережила революции, объединение Германии и рост национальных конфликтов.","Его смерть произошла во время Первой мировой войны."],"angle":"Иногда один человек становится живым мостом между эпохами — пока сама эпоха не рушится вокруг него.","importance":8,"drama":7,"visual":["Franz Joseph I photograph","Austrian emperor Franz Joseph archive photo"],"visual_kind":"photo"},
{"id":"lincoln-1865","month":4,"day":14,"year":1865,"type":"assassination","title":"Вечер, когда был убит Линкольн","event":"14 апреля 1865 года президент США Авраам Линкольн был смертельно ранен Джоном Уилксом Бутом в театре Форда.","facts":["Покушение произошло через несколько дней после капитуляции армии Роберта Ли.","Линкольн умер утром 15 апреля 1865 года."],"angle":"Гражданская война почти закончилась — и в этот момент страна потеряла президента.","importance":10,"drama":10,"visual":["Abraham Lincoln photograph 1865","Ford Theatre Lincoln historical photograph","John Wilkes Booth photograph"],"visual_kind":"photo"},
]
